spring:
  application:
    name: beauty-shop
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:~/shopDB

logging:
  level:
    root: INFO
    sql: DEBUG
    projects.portfoliodemo: DEBUG
